## Analysis of Global Urban Air Quality and Pollution

### Introduction

This project will review the most recent 12-months of air quality and pollution across the world's top 50 most populated and industrialised cities. 

The key pollutant of interest in this dataset is 'PM2_5_ug_m3', which is described as 'Fine particulate matter (μg/m³) primarily from vehicle exhaust and smog. Highly dangerous to respiratory health.'

The aim of this work is to understand which cities are facing the greatest challenges moving forward considering their current trends.

### Libraries and packages

In [1]:
### Import relevant libraries and library items.
#!pip install matplotlib
#!pip install seaborn
#!pip install scipy

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import linregress

print("\nStep 1: Complete")
print("-"*36)

Step 1: Complete
------------------------------------

### Dataset

In [2]:
### Read and display raw data.

df_0 = pd.read_csv(r"C:\Users\pierce.coveney\OneDrive - Wiltshire Council\Documents\0. PierceC\1. Apprenticeship\Y1\T3. Data Science Professional Practice\ii. Assessments\Analysis\DSProject\KaggleData\RawData.csv", index_col=None)
### Original file name was 'global_urban_smog_pm25_hourly', now called 'RawData.csv'.
df = df_0.sort_values('City')

print("\nStep 2: Complete")
print("-"*36)
display(df)

Step 2: Complete
------------------------------------

,Timestamp,City,Latitude,Longitude,PM10_ug_m3,PM2_5_ug_m3,Carbon_Monoxide_ug_m3,Nitrogen_Dioxide_ug_m3,Ozone_ug_m3,Dust_ug_m3,UV_Index,European_AQI,Hazardous_Event
149326,2026-05-22T22:00,Bangkok,13.7563,100.5018,7.0,6.0,889.0,8.6,57.0,0.0,0.00,23,0
146407,2026-01-21T07:00,Bangkok,13.7563,100.5018,31.3,29.7,1473.0,17.9,67.0,0.0,0.05,65,0
146406,2026-01-21T06:00,Bangkok,13.7563,100.5018,26.3,24.8,1166.0,12.4,70.0,0.0,0.00,65,0
146405,2026-01-21T05:00,Bangkok,13.7563,100.5018,24.4,23.1,731.0,7.7,75.0,0.0,0.00,64,0
146404,2026-01-21T04:00,Bangkok,13.7563,100.5018,22.9,21.7,434.0,4.4,79.0,0.0,0.00,64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67343,2026-01-20T23:00,Tokyo,35.6895,139.6917,11.1,10.1,222.0,29.0,41.0,0.0,0.00,52,0
67342,2026-01-20T22:00,Tokyo,35.6895,139.6917,11.6,10.7,221.0,34.1,37.0,0.0,0.00,59,0
67341,2026-01-20T21:00,Tokyo,35.6895,139.6917,10.8,10.3,220.0,37.8,34.0,0.0,0.00,61,0
67347,2026-01-21T03:00,Tokyo,35.6895,139.6917,8.1,7.1,217.0,22.7,44.0,0.0,0.00,34,0
65878,2025-11-20T22:00,Tokyo,35.6895,139.6917,48.2,46.9,872.0,72.1,1.0,0.0,0.00,76,0

### EDA

Now that we've successfully populated our dataframe, lets begin the EDA process by checking the dataset for Null values and existing data types:

In [3]:
### Display a generic summary of the dataset:

print("\nData Info:")
print("-"*36)
display(df.info())

Data Info:
------------------------------------
<class 'pandas.DataFrame'>
Index: 254736 entries, 149326 to 65878
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Timestamp               254736 non-null  str
 1   City                    254736 non-null  str
 2   Latitude                254736 non-null  float64
 3   Longitude               254736 non-null  float64
 4   PM10_ug_m3              254710 non-null  float64
 5   PM2_5_ug_m3             254736 non-null  float64
 6   Carbon_Monoxide_ug_m3   254736 non-null  float64
 7   Nitrogen_Dioxide_ug_m3  254736 non-null  float64
 8   Ozone_ug_m3             254736 non-null  float64
 9   Dust_ug_m3              254736 non-null  float64
 10  UV_Index                254736 non-null  float64
 11  European_AQI            254736 non-null  int64
 12  Hazardous_Event         254736 non-null  int64
dtypes: float64(9), int64(2), str(2)
memory usage: 27.2 MB

None

It appears that the 'Timestamp' column is incorrectly considered a string type rather than a date type.

In [4]:
### Converting the 'Timestamp' column to an actual 'datetime' column:

df["Timestamp"] = pd.to_datetime(df["Timestamp"])

display(df)

print("\nData Info:")
print("-"*36)
display(df.info())

,Timestamp,City,Latitude,Longitude,PM10_ug_m3,PM2_5_ug_m3,Carbon_Monoxide_ug_m3,Nitrogen_Dioxide_ug_m3,Ozone_ug_m3,Dust_ug_m3,UV_Index,European_AQI,Hazardous_Event
149326,2026-05-22 22:00:00,Bangkok,13.7563,100.5018,7.0,6.0,889.0,8.6,57.0,0.0,0.00,23,0
146407,2026-01-21 07:00:00,Bangkok,13.7563,100.5018,31.3,29.7,1473.0,17.9,67.0,0.0,0.05,65,0
146406,2026-01-21 06:00:00,Bangkok,13.7563,100.5018,26.3,24.8,1166.0,12.4,70.0,0.0,0.00,65,0
146405,2026-01-21 05:00:00,Bangkok,13.7563,100.5018,24.4,23.1,731.0,7.7,75.0,0.0,0.00,64,0
146404,2026-01-21 04:00:00,Bangkok,13.7563,100.5018,22.9,21.7,434.0,4.4,79.0,0.0,0.00,64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67343,2026-01-20 23:00:00,Tokyo,35.6895,139.6917,11.1,10.1,222.0,29.0,41.0,0.0,0.00,52,0
67342,2026-01-20 22:00:00,Tokyo,35.6895,139.6917,11.6,10.7,221.0,34.1,37.0,0.0,0.00,59,0
67341,2026-01-20 21:00:00,Tokyo,35.6895,139.6917,10.8,10.3,220.0,37.8,34.0,0.0,0.00,61,0
67347,2026-01-21 03:00:00,Tokyo,35.6895,139.6917,8.1,7.1,217.0,22.7,44.0,0.0,0.00,34,0
65878,2025-11-20 22:00:00,Tokyo,35.6895,139.6917,48.2,46.9,872.0,72.1,1.0,0.0,0.00,76,0

Data Info:
------------------------------------
<class 'pandas.DataFrame'>
Index: 254736 entries, 149326 to 65878
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Timestamp               254736 non-null  datetime64[us]
 1   City                    254736 non-null  str
 2   Latitude                254736 non-null  float64
 3   Longitude               254736 non-null  float64
 4   PM10_ug_m3              254710 non-null  float64
 5   PM2_5_ug_m3             254736 non-null  float64
 6   Carbon_Monoxide_ug_m3   254736 non-null  float64
 7   Nitrogen_Dioxide_ug_m3  254736 non-null  float64
 8   Ozone_ug_m3             254736 non-null  float64
 9   Dust_ug_m3              254736 non-null  float64
 10  UV_Index                254736 non-null  float64
 11  European_AQI            254736 non-null  int64
 12  Hazardous_Event         254736 non-null  int64
dtypes: datetime64[us](1), float64(9), int64(2), str(1)
memory usage: 27.2 MB

None

The context provided by the poster on Kaggle stated that the data should contain "50 of the world's most populated and industrialized megacities".

In [8]:
### Counting the unique number of strings present within the 'City' column:
cities = df['City'].unique()
print("\nIn total, there are {len(cities)} cities contained within this dataset, including:")

### Presenting a complete alphabetised list of all unqiue cities within the dataset.
sorted_cities = sorted(cities)
print(sorted_cities)
print("-"*36)

### Describing whether the number of cities contained within the dataset matches the Kaggle submission context.
if len(cities)<50:
    print("\nThere are fewer cities contained within this dataset than first stated.")
if len(cities)==50:
    print("\nThere are 50 cities contained within this dataset.")
if len(cities)>50:
    print("\nThere are more cities contained within this dataset than first stated.")

In total, there are {len(cities)} cities contained within this dataset, including:
['Bangkok', 'Beijing', 'Bogota', 'Buenos Aires', 'Cairo', 'Chicago', 'Delhi', 'Dhaka', 'Dubai', 'Istanbul', 'Jakarta', 'Johannesburg', 'Karachi', 'Lagos', 'Lahore', 'Lima', 'London', 'Los Angeles', 'Mexico City', 'Moscow', 'Mumbai', 'New York', 'Paris', 'Riyadh', 'Sao Paulo', 'Seoul', 'Shanghai', 'Tehran', 'Tokyo']
------------------------------------

There are fewer cities contained within this dataset than first stated.

The next step in the EDA process is inspecting the dataset for extreme values, with the aim being to remove outliers.

We can begin this inspection by looking at an overall summary of the quantitative data.

In [ ]:
### Assessing the summary statistics of each quantitative variable (i.e., the pollutants) within the dataset.

print("\nSummary Statistics:")
print("-"*36)
display(df.describe().T)

It would appear that each pollutant presents extreme values for the 'max' datapoint.

The key pollutant of interest in this analysis will be 'PM2_5_ug_m3', but further information might be useful for determining which values are outliers.

Using scatterplots that show these polutant levels over time per city, we can visualise where outliers may exist. An effective method of presenting this appears to be using 'Faceted plots' to produce a grid of scatterplots.

In [ ]:
### Start by defining the scatterplot grid structure.
Grid = sns.FacetGrid(df
    ,col='City'
    ,col_wrap=4      # 4x plots presented per row.
    ,height=3
    ,sharey=True     # All plots use the same y-axis scale.
)

### Next, map the variables I am interested in to the x- and y-axis respectively.
Grid.map_dataframe(sns.scatterplot
    ,x='Timestamp'
    ,y='PM2_5_ug_m3'
)

### Defining the axis labels and title for each scatter plot presented.
Grid.set_axis_labels('Timestamp', 'PM2_5_ug_m3')
Grid.set_titles('{col_name}')

### The x-axis labels are overlapping eachother, making them difficult to read.
### Remedy this by creating a function that loops through each subplot (structured as an iterable list using '.flat') and rotates the x-axis by 60 degrees. 
for axis in Grid.axes.flat:
    axis.tick_params(axis='x', rotation=60)

### Before presenting the final outputs, you can use Matplotlib to automatically adjust spacings within the visual to avoid visual problems.  
plt.tight_layout()

The array of scatterplots now presented do not show clear cases of significant outliers, but there is a sign of upward trends in some cases.

### Analysis and Modelling

Now that the scatteplots have provided an initial understanding of how these specific polution levels are trending over time in each city, lets try to understand which cities are experiencing an upward trend in their pollution figures and may face potentially dangerous levels of 'PM2_5_ug_m3' pollutants in the near future.

Trend is most commonly measured using Regression analysis. In this case, a linear regression model should be established to calculate the direction of trend for each city within the dataset.

In [ ]:
### Time series analysis with regression modelling requires a linear scale that represents time rather than a Timestamp date format.
### Start by converting the Timestamp column into the number of days since the earliest date. 
df['Days since start'] = (df['Timestamp'] - df['Timestamp'].min()).dt.days

### Begin the next step by creating an empty list to store results of the later regression model.
trend_results = []

### Since a regression analysis needs to be run for each City, create a loop through each city:
for city in df['City'].unique():

    ### In each version of the regression analysis on the dataframe 'city_df', the 'City' column is filtered to only present a single city per loop. 
    city_df = df[df['City'] == city]
    
    ### The final check, the regression should only be run if there are enough observations within the dataframe.
    if len(city_df) >= 20:
        
        regression = linregress(
            city_df['Days since start'],
            city_df['PM2_5_ug_m3']
        )
        
        slope = regression.slope
        p_value = regression.pvalue
        r_squared = regression.rvalue ** 2

        ### With the regression model parameters in place, a column titled 'trend' then describes if the trend is statistically significant. 
        if slope > 0 and p_value < 0.05:
            trend = 'Significant upward trend'
        elif slope < 0 and p_value < 0.05:
            trend = 'Significant downward trend'
        elif slope > 0:
            trend = 'Upward trend, not statistically significant'
        elif slope < 0:
            trend = 'Downward trend, not statistically significant'
        else:
            trend = 'No trend'

        ### The outputs of the regression model are finally presented by populating the empty list created at the start. 
        trend_results.append({
            'City': city,
            'Number of records': len(city_df),
            'Slope per day': slope,
            'P-value': p_value,
            'R-squared': r_squared,
            'Trend': trend
        })

### The looping regression model results are then converted to a dataframe for easier sorting and presentation.
trend_summary = pd.DataFrame(trend_results)

### Outputs are sorted so the greatest upward slopes appear first.
trend_summary = trend_summary.sort_values(
    by='Slope per day',
    ascending=False
)

trend_summary

### Results

The final results appear to show that Riyadh has not only experienced the highest levels of pollutants sourced primarily from vehicle exhaust and smog, ahead of Shanghai and Beijing, but it is also presenting the largest upward trend in this pollutant level in the past 12 months.

Visual analysis of scatterplots presents clear seasonal trends across most of these cities, where these pollutant levels appear to rise during colder months, but Riyadh presents consistently high levels with these pollutants spiking in both winter and summer.

In contrast, Jakarta presents the largest statistically significant downward trend among the cities present here. Jakarta presents consistent pollutant levels throughout the 12-month period without sign of seasonality. This result would benefit from further analysis to understand why these changes might be occuring.